# Introduction to Python programming
Dr. Manfred Eppe

Material partially adapted from J.R. Johansson (jrjohansson at gmail.com) [http://github.com/jrjohansson/scientific-python-lectures](http://github.com/jrjohansson/scientific-python-lectures).

<b>Python:</b>
* #1 Programming language in Data Science and AI
* Lots of code available (e.g. github, kaggle), great community support
* Interpreted language (no compilation necessary)
* Clean syntax, object oriented, powerful extensions. E.g. numpy package for statistical AI processing
* Jupyter notebooks (.ipynb files) allow for step-wise execution (used in the lectures) to illustrate code
* Sophisticated IDEs available (we’ll use Pycharm in the exercises and the projects)

### A simple code snippet with if-then-else control-flow

In [ ]:
x = 5 - 4     # comment: integer difference
y = "Hallo"

if x == 0 or y == "Hello":
    y = y + " World"  # concatenate string
else:
    y = y + " Moon"  # concatenate string

print(x)
print(y)

print(y + "abcd")

1
Hallo Moon
Hallo Moonabcd


* Assignment uses =  and comparison uses  ==
* \+ - * / %  compute numbers as expected. Use + also for string concatenation
* Logical operators are words (`and`, `or`, `not`), not symbols (&&, ||, !)
* First assignment of a variable will create it (no declaration necessary)
* Python auto-assigns the variable types e.g. `number = 0.0` is `float` and `number = 0` is `int`
* Indentation controls program structure

### Function definitions and docstrings

* Functions can be created with the `def` keyword
* A docstring under the header of a function can be used to explain the function's purpose
* Can be used to auto-generate a full code documentation with Sphinx

In [ ]:
def my_function(x, y):
  """This is the docstring. This function computes x to the power of y. It also prints the sum of x and y.

     :param x: a number
     :param y: a number
     :returns: x^y
     """

  print(x - y)
  return x ** y # computes x^y

pwr = my_function(4,5)
print(pwr)

-1
1024



### Data types and errors

In [ ]:
x = "the answer is "    # x is string
y = 42  # y is integer
print(type(y))
z = x + y               # Python complains
print(z)
print("The script terminates with an error") # This will not be executed because the script terminates with an error.

<class 'int'>


TypeError: can only concatenate str (not "int") to str

Explicit type conversion:

In [ ]:
y_str = str(y)          # y_str is string
print(type(y_str))
x + y_str

<class 'str'>


'the answer is 42'

### Catching exceptions


In [ ]:
x = "answer "
y = 2
try:
    print(x + y)
    print("result is done successfully")
except Exception as e:
    print("this is error block")
    print(e)

print("This script continues") # This will be executed because the Exception has been caught.


this is error block
can only concatenate str (not "int") to str
This script continues


### Basic string operations

* \+ can be used for string concatenation
* A string is an array of characters, so individual characters can be accessed with `[]` (more on arrays later)
* A very convenient method to generate and concatenate strings is to use the `.format` function in combination with formatted placeholders `{}`, `{:.2f}`.
* `.2f` specifies that we want to convert a float to a string and only use 2 decimal places.

In [ ]:
sample_string = "hello"
print(sample_string.upper())
print(str.upper(sample_string))    # same

HELLO
HELLO


In [ ]:
sample_string = "allegory"
print(sample_string + sample_string)
print(sample_string[3:7])
#0 a
#1 l
#2 l
#3 e
#4 g
#5 o
#6 r
#7 y

allegoryallegory
egor


In [ ]:
z1 = 1.234
z2 = 5.678
z3 = 1/3
print(z3)
number_format_str = "Number format: {:.2f}, {}".format(z3, z2)

cat_number = 6
cat_name = "Jello"

story_str = "I have {} cats, the first cat's name is {}".format(cat_number, cat_name)
print(number_format_str)
print(story_str)

0.3333333333333333
Number format: 0.33, 5.678
I have 6 cats, the first cat's name is Jello


### File operations

* File objects can be generated with the `open` command.
* Files should be closed after reading/writing.
    * open file limit
    * write operations not guaranteed to happen until closing
    * otherwise Python will close files automatically, but it is not perfect at this

In [ ]:
x = 12
fobj = open("new_file_3.txt", "w") # 'w' for open in (over)write mode
fobj.write("i have {} cats".format(x))
fobj.close()

fobj = open("new_file.txt", "w") # 'w' for open in (over)write mode
fobj.write("values: {:.2f}\n".format(1.234))
fobj.close()


fobj = open("new_file.txt", "r") # 'r' for open in read mode
data = fobj.read()
fobj.close()
print(data)

values: 1.23



In [ ]:
fobj = open("new_file.txt", "a") # 'a' for open in write append mode
fobj.write("values: {:.2f}\n".format(5.678))
fobj.close()

fobj = open("new_file.txt", "r") # 'r' for open in read mode
data = fobj.read()
fobj.close()
print(data)


### Lists

**Lists** are defined using square brackes. Accessing an element or a range of an element is possible using the slicing notation as for strings. Appending to a list is possible with the `append()` function or with `+`.

In [30]:
my_list = [1,2,3,4,5] # A list with 5 elements
print(my_list)

my_list2 = [] # An empty list
print(my_list2)

my_list2.append(4) # Adding 4 to the empty list
print(my_list2)

new_list = my_list + my_list2 # Concatenation of two lists
print(new_list)

[1, 2, 3, 4, 5]
[]
[4]
[1, 2, 3, 4, 5, 4]


Lists can also be defined as a range (note, `range(5)` does not include 5)

In [33]:
range1 = range(5)
print(range1)
range_list1 = list(range1)
print(range_list1)

range2 = range(-5,5)
print(range2)


range(0, 5)
[0, 1, 2, 3, 4]
range(-5, 5)


To convert a range into a list use a typecast. However, note that a range inherits all operations from lists, so the typecast is usually not necessary.

In [32]:
range_list2 = list(range2)
print(range_list2)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]


To access an element of the list, you can specify an index with square brackets:

In [ ]:
print(range_list2[2]) # will print the third element of the list, because indices start at 0.

You can also _slice_ the list with the `[from(inclusive):to(exclusive)]` notation.
If _from_ or _to_ is not specified, it defaults to the first/last element in the list.

In [34]:
list_2 = [-5,-4,-3,-2,-1,0,1,2,3,4]
print(list_2[0:2]) # first 2 elements of the list
print(list_2[:2]) # same, empty before : is assumed zero (0)
print(list_2[5:]) # 6th to last element, empty after : is assumed last element

[-5, -4]
[-5, -4]
[0, 1, 2, 3, 4]


To select the n-th last element of a list, it is possible to use the following notation:

In [41]:
second_last = range2[-2]
print(second_last)
from_third_last_to_end = range_list2[-3:]
print(from_third_last_to_end)
from_second_to_second_last = range_list2[2:-2]
print(from_second_to_second_last)

list_3 = ["a","b","c","d","e","f","g","h","i","j"]
print(list_3[-2])
print(list_3[-3:])
print(list_3[2:-2])
print(list_3[2:8])

#  a   b  c  d  e  f  g  h  i  j
#  0   1  2  3  4  5  6  7  8  9 -> index
# -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 -> negative index

3
[2, 3, 4]
[-3, -2, -1, 0, 1, 2]
i
['h', 'i', 'j']
['c', 'd', 'e', 'f', 'g', 'h']
['c', 'd', 'e', 'f', 'g', 'h']


<!-- print("parameter1 = " + str(params["parameter1"]))
print("parameter2 = " + str(params["parameter2"]))
print("parameter3 = " + str(params["parameter3"]))
print("parameter4 = " + str(params["parameter4"])) -->


### Loops
In Python, loops can be programmed in a number of different ways. The most common is the `for` loop, which is used together with iterable objects, such as lists. The basic syntax is:

In [45]:
print("loop print [1,2]")
for x in [1,2]:
    print(x)

print("loop print animal")
animal = ["chicken", "girrafe", "elephant", "bear", "lion"]

for a in animal:
    print("there is {} in the zoo".format(a))

loop print [1,2]
1
2
loop print animal
there is chicken in the zoo
there is girrafe in the zoo
there is elephant in the zoo
there is bear in the zoo
there is lion in the zoo


In [ ]:
for word in ["scientific", "computing", "with", "python"]:
    print(word)

With enumerate, you can iterate through this indices of a list, and with len() you can determine the length of a list as follows:

In [49]:
print(list(enumerate(animal)))

for i,anm in enumerate(animal):
    print("{}. There is {} in the zoo".format(i+1, anm))


[(0, 'chicken'), (1, 'girrafe'), (2, 'elephant'), (3, 'bear'), (4, 'lion')]
1. There is chicken in the zoo
2. There is girrafe in the zoo
3. There is elephant in the zoo
4. There is bear in the zoo
5. There is lion in the zoo


**Little exercise:** Use a loop to print the product of the i-th and the i+1-th element of `range_list2`. Be careful with the last element of the list; if i is the last element of the list, use if-then to set i to 0.

In [56]:
"""
range2 = [-5,-4,-3,-2,-1,0,1,2,3,4]
print(-5 * -4)
print(-4 * -3)
print(-3 * -2)
print(-2 * -1)
print(-1 * 0)
print(0 * 1)
print(1 * 2)
print(2 * 3)
print(3 * 4)
print(4 * -5)


"""

print("alternative 1")
for i,j in enumerate(range2):
    #print("i: {}, j: {}".format(i,j))
    idx2 = (i + 1) % (len(range2))
    #print(idx2)
    result = range2[i] * range2[idx2]
    #print(result)
    # result = i-th element * i+1-th element

    # print(result)

print("alternative 2")
for i,n in enumerate(range2):

  if (i == len(range2)-1):
    m = range2[0]
  else:
    m = range2[i+1]
  print("{} x {} = ".format(n, m))

alternative 1
alternative 2
-5 x -4 = 
-4 x -3 = 
-3 x -2 = 
-2 x -1 = 
-1 x 0 = 
0 x 1 = 
1 x 2 = 
2 x 3 = 
3 x 4 = 
4 x -5 = 


### Dictionaries

Dictionaries are also like lists, except that each element is a key-value pair. The syntax for dictionaries is `{key1 : value1, ...}`:

In [57]:
params = {"key1" : 1.0,
          "key2" : 2.0,
          "key3" : 3.0,}
print(params)

{'key1': 1.0, 'key2': 2.0, 'key3': 3.0}


In [58]:
print("parameter1 = {}".format(params["key1"]))
print("parameter2 = {}".format(params["key2"]))
print("parameter3 = {}".format(params["key3"]))

parameter1 = 1.0
parameter2 = 2.0
parameter3 = 3.0


In [ ]:
# overwrite params
params["key1"] = "A"
params["key2"] = "B"
# add a new entry
params["key4"] = 4.5
params

To iterate over key-value pairs of a dictionary:

In [61]:
print(list(params.items()))
for key, value in params.items():
    print(key + " = " + str(value))

key_list = params.keys()
print(key_list)
value_list = params.values()
print(value_list)

[('key1', 1.0), ('key2', 2.0), ('key3', 3.0)]
key1 = 1.0
key2 = 2.0
key3 = 3.0
dict_keys(['key1', 'key2', 'key3'])
dict_values([1.0, 2.0, 3.0])


### List comprehensions: Creating lists using `for` loops:

A convenient and compact way to initialize lists:

In [62]:
# Verbose method:
l_much_code = []
for x in range(0,5):
    l_much_code.append(x**2)
print(l_much_code)

# Compressed method
l_less_code = [x**2 for x in range(0,5)]
"""
[
  x**2 => [0**2, 1**2, 2*2, 3**2, 4**2] => [0, 1, 4, 9, 16]
  for x in range(0,5) => [0,1,2,3,4]
]
"""

print(l_less_code)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]


### `while` loops:

In [63]:
i = 0
while i < 5:
    print(i)
    i = i + 1
print("done")

0
1
2
3
4
done


In [64]:
i = 0
while True:
    if i == 6:
        break # break causes loop to abort
    i = i + 1
    if i == 4:
        continue # When continue is hit, the interpreter jumps to loop head
    print(i)

print("done")

1
2
3
5
6
done


### Module import
External libraries (aka. packages/modules), provide very powerful functionalities. There exist pre-existing libraries to plot data, to implement neural nets, or to access databases.

To access external libraries, Python uses the ``import`` statement.

In [ ]:
import math
x = math.cos(2 * math.pi)
x


Alternatively, import all symbols (functions and variables) in a module to the current namespace, so that you don't need to use the prefix "`math.`" every time you use something from the `math` module:

In [ ]:
def cos(x):
    return x**2

from math import *
x = cos(2 * pi)
x

This pattern can be very convenient, but in large programs that include many modules it is often a good idea to keep the symbols from each module in their own namespaces, by using the `import math` pattern. This would elminate potentially confusing problems with name space collisions.

As a third alternative, we can chose to import only a few selected symbols from a module by explicitly listing which ones we want to import instead of using the wildcard character `*`:

In [66]:
from math import cos, pi
x = cos(2/3 * pi)
print(x)

-0.4999999999999998


Sometimes it is useful to create an alias for a module

In [ ]:
import math as m

x = m.cos(2)

### Numpy basics

Numpy is all about vector algebra. Its core data structure is multi-dimensional arrays. It is THE package for deep learning and data science.


In [75]:
import numpy
a = numpy.zeros((6,3)) # Create a 2x3 matrix consisting of zeros
print(a)

from numpy import random
b = random.normal(12.3,0.001,(3,2))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[12.29931258 12.2994869 ]
 [12.30044738 12.29989142]
 [12.29750008 12.29928742]]



### Numpy arrays vs. lists

In [78]:
import numpy as np
a = np.array([[1,2],[3,4]])
x = a[0,1]     # 1st element of 0th row
y = a[0,:]     # 0th row
z = a[:,0]     # 0th column

print(x)
print(y)
print(z)

2
[1 2]
[1 3]


This does not work with python lists:

In [77]:
a2=[[1,2],[3,4]]
try:
    print(a2[0][1])
    x2 = a2[0,1]
except Exception as e:
    print("Error: {}".format(e))


2
Error: list indices must be integers or slices, not tuple


In [ ]:
x2 = a2[0][1]    # 1st element of 0th row
print(x2)
y2 = a2[0][:]    # 0th row
print(y2)
z2 = a2[:][0]  # NOT 0th column (because a2[:] == a2)
print(z2) # Different from the z above!!!

### Fast and slow Python: external modules often provide high performance
Add 3 times the dot product $z=\sum\limits_{i=1}^{3}(y \cdot x)$

In [80]:
import numpy, time

# dot product operation, build the function ourselves, using default python's functions

x = numpy.ones(10000)
y = numpy.ones((400,10000))
z = numpy.zeros(400)
now = time.perf_counter() # Add 10 times the dot product y.z
for i in range(3):
  for i in range (400):
    for j in range (10000):
      z[i] += y[i][j]*x[j]
duration = time.perf_counter() - now
print(duration)

10.768354587999056


In [81]:
# dot product operation, use numpy module (numpy.dot)

now = time.perf_counter()
for i in range(3):
  z += numpy.dot(y, x)
duration = time.perf_counter() - now
print(duration) # The built in function is MUCH faster! More on this later!

0.012509085001511266



### Pitfall: Inconsistent modules

In [79]:
import numpy
import random
n = numpy.zeros(15)
r = numpy.zeros(15)
for i in range (15):
    n[i] = numpy.random.randint(0,2)   # 0 <= n[i] < 2
    r[i] = random.randint(0,2)         # 0 <= r[i] < 3 !
print(' n={} \n r={}'.format(n,r))

 n=[1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0.] 
 r=[0. 2. 2. 2. 2. 1. 2. 1. 2. 2. 1. 1. 2. 1. 2.]


In [82]:
from numpy import random, zeros

r = zeros(15)

for i in range (15):
    r[i] = random.randint(0,2)
print(' r = {}'.format(r))

 r = [0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0.]



### Assignments are by reference

Non-fundamental datatypes are assigned by reference

In [83]:
a = [1,2,3]
b = a # This does not make a copy, b becomes the same object as a
a.append(7) # Therefore, if a is changed, b will change as well
print(a)
print(b)

[1, 2, 3, 7]
[1, 2, 3, 7]


In [84]:
x = 5
y = x
x = x+1
print(x)
print(y)

6
5


In [85]:
# To avoid change, create a copy:
a = [1,2,3]
b = a.copy()
a.append(7)
print(b)

[1, 2, 3]


Fundamental datatypes (e.g. int, float, bool) are assigned by value

In [ ]:
a = 7
b = a # This is a basic data type (an integer), so b does NOT become the same object as a
a += 2 # Therefore, if a is changed, b will not change as well
print(b)

Operations often create a copy

In [ ]:
a = [1,2,3]
c = a[1:] # The slice operation creates a copy
print(c)
a.append(7)
print(c) # c is unchanged

In [ ]:
a = [1,2,3]
d = numpy.array(a) # Creating a numpy array from a list also creates a copy
a.append(7)
print(d)

### Pitfall: Function arguments are also passed by reference

In [86]:
def update_dict(d):
   new_d={'alok':30,'Nevadan':28}
   d.update(new_d)
   print("Inside the function",d)
   return d

student={'Archana':28,'krishna':25,'Ramesh':32,'vineeth':25}

print(student)

{'Archana': 28, 'krishna': 25, 'Ramesh': 32, 'vineeth': 25}


In [87]:
new_student = update_dict(student)
print(new_student)


Inside the function {'Archana': 28, 'krishna': 25, 'Ramesh': 32, 'vineeth': 25, 'alok': 30, 'Nevadan': 28}
{'Archana': 28, 'krishna': 25, 'Ramesh': 32, 'vineeth': 25, 'alok': 30, 'Nevadan': 28}


In [ ]:
print(student)

In [90]:
def my_append(li):
  li.append(7)

def my_add(a):
  a += 1

list1= [1,2,3]
my_append(list1.copy())

x = 4
my_add(x)

print(list1)
print(x)

[1, 2, 3]
4


### Copies of objects
To avoid accidental changes to a variable, make a copy!

In [ ]:
a = numpy.ones(3)
b = my_funct2(a.copy()) # To avoid accidental changes to a variable, make a copy!
print(b)
print(a) # a is still the same because a copy has been passed to the function


### Object-oriented programming: classes


In [92]:
class Stack:
   def __init__(self):
      print("calling Stack() --> calling constructor __init__")
      self.items = [0]
   def push(self, x):
      self.items.append(x)
   def push2(self, x):
      self.items.append(x)
      self.items.append(x)

   def pop(self):
      x = self.items[-1]
      del self.items[-1]
      return x
   def empty(self):
      print("checking if items is empty")
      return len(self.items) == 0



In [93]:
t = Stack()
print(t.empty())
print("t items", t.items)
t.push2("hello")
print(t.empty())
print("t items", t.items)
a = t.pop()
print(a)
print(t.empty())
print("t items", t.items)
b = t.pop()
print(b)
print(t.empty())
print(t)

calling Stack() --> calling constructor __init__
checking if items is empty
False
t items [0]
checking if items is empty
False
t items [0, 'hello', 'hello']
hello
checking if items is empty
False
t items [0, 'hello']
hello
checking if items is empty
False


## Summary
* Python language primitives
* Types
* Control structures: Conditions and loops
* Dictionaries and strings
* File operations
* Functions
* Exceptions
* Module import
* Numpy package (...to be continued)
* Pass by value vs. pass by reference
* Classes

<center>Thank you!</center>